export const EDIT_PROFILE = "EDIT_PROFILE";
export const EDITED_PROFILE = "EDITED_PROFILE";

export const DELETE_TEACHER = "DELETE_TEACHER";
export const DELETED_TEACHER = "DELETED_TEACHER";

export const ADD_TEACHER = "ADD_TEACHER";
export const ADDED_TEACHER = "ADDED_TEACHER";

export const LOGIN = "LOGIN";
export const LOGGED_IN = "LOGGED_IN";

export const GET_TEACHERS_LOADING = "GET_TEACHERS_LOADING";
export const GET_TEACHERS_SUCCESS = "GET_TEACHERS_SUCCESS";
export const GET_TEACHERS_ERROR = "GET_TEACHERS_ERROR"

export const ADD_PHOTO_LOADING = "ADD_PHOTO_LOADING";
export const ADD_PHOTO_SUCCESS = "ADD_PHOTO_SUCCESS";
export const ADD_PHOTO_ERROR = "ADD_PHOTO_ERROR";

export const GET_PHOTOS_LOADING = "GET_PHOTOS_LOADING";
export const GET_PHOTOS_SUCCESS = "GET_PHOTOS_SUCCESS";
export const GET_PHOTOS_ERROR = "GET_PHOTOS_ERROR";

export const ADD_WORKER = "ADD_WORKER";
export const ADDED_WORKER = "ADDED_WORKER";

export const GET_WORKER_LOADING = "GET_WORKER_LOADING";
export const GET_WORKER_SUCCESS = "GET_WORKER_SUCCESS";
export const GET_WORKER_ERROR = "GET_WORKER_ERROR";

